server:
  port: 9090
  servlet:
    context-path: /cloud-manager

#Spring
spring:
  #文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/2023_campusepidemicwechat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      max-idle: 20
      min-idle: 1
      max-wait: 60000

  #freemarker 模板引擎
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/views/
    request-context-attribute: request
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    expose-session-attributes: true
    settings:
      tag_syntax: auto_detect
      template_update_delay: 0
      default_encoding: UTF-8
      output_encoding: UTF-8
      locale: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: #.##
      boolean_format: true,false
      template_exception_handler: html_debug

#MyBatis
mybatis:
  type-aliases-package: com.myclouds.manager.pojo
  mapper-locations: classpath:/mapper/*.xml

#Mybatis Sql 打印
logging:
  level:
    com.myclouds.manager.mapper: debug
